[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  BASE_NAME = ""
  GITHUB_API_URL = "https://api.github.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
