[build]
  # NOTE: rustup toolchain install してから npm i しないと wasm-pack がうまく動かないことがある。
  command = """
  rustup toolchain install stable && \
  npm ci && \
  make check && \
  make
  """
  publish = "dist/"

[build.environment]
  TZ = "Asia/Tokyo" # for snapshots
  BASE_NAME = ""
  GITHUB_API_URL = "https://api.github.com"
  USER_SERVICE_URL = "http://localhost:14566" # TODO: Deploy a User Service
  GTM_URL = "https://www.googletagmanager.com"
  GTM_CONTAINER_ID = "GTM-NNPT3D7"
  SHEETS_API_URL = "https://sheets.googleapis.com/v4"
  GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID = "1o0SaDmkwl0kNS1EUz01lzWcq9KoOG22bS_qvu0jjPCA"
  GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME = "シート1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
