[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  BASE_NAME = ""
  GITHUB_API_URL = "https://api.github.com"
  USER_AUTHN_API_URL = "http://localhost:14566" # TODO: deploy a User Authn API

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
