[build]
  command = """\
rustup toolchain install stable
npm ci
npm run build
"""
  publish = "dist/"

[build.environment]
  BASE_NAME = ""
  GITHUB_API_URL = "https://api.github.com"
  USER_SERVICE_URL = "http://localhost:14566" # TODO: Deploy a User Service
  GTM_URL = "https://www.googletagmanager.com"
  GTM_CONTAINER_ID = "GTM-NNPT3D7"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
