[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  BASE_URL = "https://gifted-hermann-57a8fb.netlify.com"
  GITHUB_API_URL = "https://api.github.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
