on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      NODE_ENV: production
      BASE_NAME: ''
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://localhost:14566 # TODO: Deploy a User Service
      GTM_URL: https://example.com
      GTM_CONTAINER_ID: GTM-0000000
      SHEETS_API_URL: https://example.com # NOTE: Use the real API only on Netlify.
      GOOGLE_CLOUD_APIS_GOOGLE_SHEETS_API_KEY: api-key
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID: sheet-id
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME: Sheet1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          make typed
          make
    strategy:
      matrix:
        node-version:
          - 20
  test:
    env:
      NODE_ENV: test
      TZ: Asia/Tokyo # for snapshots
      BASE_NAME: ''
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://example.com
      GTM_URL: https://example.com
      GTM_CONTAINER_ID: GTM-0000000
      SHEETS_API_URL: https://example.com
      GOOGLE_CLOUD_APIS_GOOGLE_SHEETS_API_KEY: 'api-key'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID: 'sheet-id'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME: 'Sheet1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint & Test
        run: |
          npm ci
          make check
    strategy:
      matrix:
        node-version:
          - 20
