on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      NODE_ENV: production
      BASE_NAME: ''
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://localhost:14566 # TODO: Deploy a User Service
      GTM_URL: https://www.googletagmanager.com
      GTM_CONTAINER_ID: GTM-NNPT3D7
      SHEETS_API_URL: https://sheets.googleapis.com/v4
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID: 1o0SaDmkwl0kNS1EUz01lzWcq9KoOG22bS_qvu0jjPCA
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME: シート1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          make typed
          make
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/
        if: github.event_name == 'push'
    strategy:
      matrix:
        node-version:
          - 18
  test:
    env:
      NODE_ENV: test
      TZ: Asia/Tokyo # for snapshots
      BASE_NAME: ''
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://example.com
      GTM_URL: https://example.com
      GTM_CONTAINER_ID: GTM-0000000
      SHEETS_API_URL: https://example.com
      GOOGLE_CLOUD_APIS_GOOGLE_SHEETS_API_KEY: 'api-key'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID: 'sheet-id'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME: 'Sheet1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint & Test
        run: |
          npm ci
          make check
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: github.event_name == 'push'
    strategy:
      matrix:
        node-version:
          - 18
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.install.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v2
      - uses: actions/deploy-pages@v2
        id: install
    needs:
      - build
      - test
    if: github.event_name == 'push'
