on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      NODE_ENV: production
      BASE_NAME: /rap
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://localhost:14566 # TODO: Deploy a User Service
      GTM_CONTAINER_ID: ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Build GitHub Pages Custom 404 Page
        run: |
          # npm ci
          npm run gulp buildGhPagesCustom404Page
          cp -r gh-pages/dist/* dist/
        if: matrix.node-version == 10
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
        if: matrix.node-version == 14
    strategy:
      matrix:
        node-version:
          - 12
          - 14
  test:
    env:
      NODE_ENV: test
      TZ: Asia/Tokyo # for snapshots
      BASE_NAME: ''
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://localhost:14566
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint & Test
        run: |
          npm ci
          npm run gulp lint
          npm test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.node-version == 14
    strategy:
      matrix:
        node-version: [12, 14]
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
    needs:
      - build
      - test
