on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      NODE_ENV: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Ensure .env
        run: |
          ln -s .env.example .env
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          npm run build
    strategy:
      matrix:
        node-version: [8, 10, 12]
