on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      NODE_ENV: production
      BASE_NAME: /rap
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://localhost:14566 # TODO: Deploy a User Service
      GTM_URL: https://example.com
      GTM_CONTAINER_ID: GTM-0000000
      SHEETS_API_URL: https://example.com # NOTE: Use the real API only on Netlify.
      GOOGLE_CLOUD_APIS_GOOGLE_SHEETS_API_KEY: 'api-key'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID: 'sheet-id'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME: 'Sheet1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm ci
          make typed
          make
      - name: Build GitHub Pages Custom 404 Page
        run: |
          # npm ci
          make gh-pages/dist
          cp -r gh-pages/dist/* dist/
        if: matrix.node-version == 16
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
        if: >-
          matrix.node-version == 16
          && github.event_name == 'push'
    strategy:
      matrix:
        node-version:
          - 16
          - 17
  test:
    env:
      NODE_ENV: test
      TZ: Asia/Tokyo # for snapshots
      BASE_NAME: ''
      GITHUB_API_URL: https://api.github.com
      USER_SERVICE_URL: http://example.com
      GTM_URL: https://example.com
      GTM_CONTAINER_ID: GTM-0000000
      SHEETS_API_URL: https://example.com
      GOOGLE_CLOUD_APIS_GOOGLE_SHEETS_API_KEY: 'api-key'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_ID: 'sheet-id'
      GOOGLE_SHEETS_FOSS_COMPARISON_TABLE_SHEET_SHEET_NAME: 'Sheet1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint & Test
        run: |
          npm ci
          make check
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.node-version == 16
    strategy:
      matrix:
        node-version:
          - 16
          - 17
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
    needs:
      - build
      - test
    if: github.ref == 'refs/heads/master'
